# Phase 52: the exported C symbols of the shim are exactly the v1 list, unmangled. Usage: cmake -DNM=<nm> -DLIB=<libtbccl_c.a> -DGOLDEN=<file> -P check_symbols.cmake
execute_process(COMMAND ${NM} -g --defined-only ${LIB} OUTPUT_VARIABLE out RESULT_VARIABLE rc ERROR_QUIET)
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "nm failed on ${LIB}")
endif()
string(REPLACE "\n" ";" lines "${out}")
set(found "")
foreach(line IN LISTS lines)
    if(line MATCHES "^[0-9a-fA-F]+ [TtSs] +_?(tbccl[A-Za-z0-9_]*)$")
        list(APPEND found "${CMAKE_MATCH_1}")
    endif()
    if(line MATCHES "^[0-9a-fA-F]+ T +_?_Z.*tbccl.*c_api")
        message(FATAL_ERROR "a C API entry point is mangled: ${line}")
    endif()
endforeach()
list(REMOVE_DUPLICATES found)
list(SORT found)
file(STRINGS ${GOLDEN} expected)
list(SORT expected)
if(NOT "${found}" STREQUAL "${expected}")
    message(FATAL_ERROR "exported C symbols differ from the v1 list.\nfound:    ${found}\nexpected: ${expected}")
endif()
list(LENGTH found n)
message(STATUS "[PASS] ${n} exported tbccl* C symbols match tests/c_api/abi_symbols_v1.txt, all unmangled")
